//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Core.Domain.Resources {
    using System;


    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSO.Core.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BAYSOFT.Builder.
        /// </summary>
        public static string BAYSOFT {
            get {
                return ResourceManager.GetString("BAYSOFT", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Code.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Loading... --.
        /// </summary>
        public static string ___Loading______ {
            get {
                return ResourceManager.GetString("-- Loading... --", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; cannot be 0!.
        /// </summary>
        public static string @__PropertyName___cannot_be_0_ {
            get {
                return ResourceManager.GetString("\'{PropertyName}\' cannot be 0!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; cannot be empty!.
        /// </summary>
        public static string @__PropertyName___cannot_be_empty_ {
            get {
                return ResourceManager.GetString("\'{PropertyName}\' cannot be empty!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; cannot be null!.
        /// </summary>
        public static string @__PropertyName___cannot_be_null_ {
            get {
                return ResourceManager.GetString("\'{PropertyName}\' cannot be null!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; is required!.
        /// </summary>
        public static string @__PropertyName___is_required_ {
            get {
                return ResourceManager.GetString("\'{PropertyName}\' is required!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; not found!.
        /// </summary>
        public static string @__PropertyName___not_found_ {
            get {
                return ResourceManager.GetString("\'{PropertyName}\' not found!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{3}&apos; must have a maximum of &apos;{1}&apos; characters!.
        /// </summary>
        public static string @__PropertyName___must_have_a_maximum_of___MaxLength___characters_ {
            get {
                return ResourceManager.GetString("\'{PropertyName}\' must have a maximum of \'{MaxLength}\' characters!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{3}&apos; must have at least &apos;{0}&apos; characters!.
        /// </summary>
        public static string @__PropertyName___must_have_at_least___MinLength___characters_ {
            get {
                return ResourceManager.GetString("\'{PropertyName}\' must have at least \'{MinLength}\' characters!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} not found!.
        /// </summary>
        public static string _0__not_found_ {
            get {
                return ResourceManager.GetString("{0} not found!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {first_item}-{last_item} of {all_items}.
        /// </summary>
        public static string _first_item___last_item__of__all_items_ {
            get {
                return ResourceManager.GetString("{first_item}-{last_item} of {all_items}", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add {0}.
        /// </summary>
        public static string Add__0_ {
            get {
                return ResourceManager.GetString("Add {0}", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add new {0}.
        /// </summary>
        public static string Add_new__0_ {
            get {
                return ResourceManager.GetString("Add new {0}", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred while saving the entity changes. See the inner exception for details..
        /// </summary>
        public static string An_error_occurred_while_saving_the_entity_changes__See_the_inner_exception_for_details_ {
            get {
                return ResourceManager.GetString("An error occurred while saving the entity changes. See the inner exception for de" +
                        "tails.", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create new {0}.
        /// </summary>
        public static string Create_new__0_ {
            get {
                return ResourceManager.GetString("Create new {0}", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you really want to delete these records? This process cannot be undone..
        /// </summary>
        public static string Do_you_really_want_to_delete_these_records__This_process_cannot_be_undone_ {
            get {
                return ResourceManager.GetString("Do you really want to delete these records? This process cannot be undone.", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit {0}.
        /// </summary>
        public static string Edit__0_ {
            get {
                return ResourceManager.GetString("Edit {0}", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter your query here....
        /// </summary>
        public static string Enter_your_query_here___ {
            get {
                return ResourceManager.GetString("Enter your query here...", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Loading....
        /// </summary>
        public static string Loading___ {
            get {
                return ResourceManager.GetString("Loading...", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No matching records found.
        /// </summary>
        public static string No_matching_records_found {
            get {
                return ResourceManager.GetString("No matching records found", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operation failed in domain validation!.
        /// </summary>
        public static string Operation_failed_in_domain_validation_ {
            get {
                return ResourceManager.GetString("Operation failed in domain validation!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operation failed in entity validation!.
        /// </summary>
        public static string Operation_failed_in_entity_validation_ {
            get {
                return ResourceManager.GetString("Operation failed in entity validation!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operation failed in request validation!.
        /// </summary>
        public static string Operation_failed_in_request_validation_ {
            get {
                return ResourceManager.GetString("Operation failed in request validation!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rows per page:.
        /// </summary>
        public static string Rows_per_page_ {
            get {
                return ResourceManager.GetString("Rows per page:", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successful operation!.
        /// </summary>
        public static string Successful_operation_ {
            get {
                return ResourceManager.GetString("Successful operation!", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unsuccessful operation!.
        /// </summary>
        public static string Unsuccessful_operation_ {
            get {
                return ResourceManager.GetString("Unsuccessful operation!", resourceCulture);
            }
        }
    }
}