using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BAYSOFT.Infrastructures.Data.Default.Migrations
{
    /// <inheritdoc />
    public partial class InitialDMLMigrationDefaultDbContext : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                schema: "DefaultDb",
                table: "Samples",
                columns: new[] { "Id", "Description" },
                values: new object[,]
                {
                    { Guid.Parse("00000000-0000-0000-0000-000000000001"), $"Sample 01 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000002"), $"Sample 02 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000003"), $"Sample 03 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000004"), $"Sample 04 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000005"), $"Sample 05 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000006"), $"Sample 06 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000007"), $"Sample 07 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000008"), $"Sample 08 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000009"), $"Sample 09 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000010"), $"Sample 10 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000011"), $"Sample 11 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000012"), $"Sample 12 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000013"), $"Sample 13 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000014"), $"Sample 14 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                    { Guid.Parse("00000000-0000-0000-0000-000000000015"), $"Sample 15 generated by migration at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}" },
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "DefaultDb",
                table: "Samples",
                keyColumn: "Id",
                keyValues: new object[]
                {
                    Guid.Parse("00000000-0000-0000-0000-000000000001"),
                    Guid.Parse("00000000-0000-0000-0000-000000000002"),
                    Guid.Parse("00000000-0000-0000-0000-000000000003"),
                    Guid.Parse("00000000-0000-0000-0000-000000000004"),
                    Guid.Parse("00000000-0000-0000-0000-000000000005"),
                    Guid.Parse("00000000-0000-0000-0000-000000000006"),
                    Guid.Parse("00000000-0000-0000-0000-000000000007"),
                    Guid.Parse("00000000-0000-0000-0000-000000000008"),
                    Guid.Parse("00000000-0000-0000-0000-000000000009"),
                    Guid.Parse("00000000-0000-0000-0000-000000000010"),
                    Guid.Parse("00000000-0000-0000-0000-000000000011"),
                    Guid.Parse("00000000-0000-0000-0000-000000000012"),
                    Guid.Parse("00000000-0000-0000-0000-000000000013"),
                    Guid.Parse("00000000-0000-0000-0000-000000000014"),
                    Guid.Parse("00000000-0000-0000-0000-000000000015")
                });
        }
    }
}
